# Generated by Django 5.2.16 on 2026-09-10 11:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_accounts', '0005_remove_socialconnection_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccountCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('encrypted_access_token', models.TextField()),
                ('token_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('ERROR', 'Error')], db_index=True, default='ACTIVE', max_length=20)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('social_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_credential', to='social_accounts.socialaccount')),
            ],
            options={
                'db_table': 'instagram_account_credentials',
                'indexes': [models.Index(fields=['status', 'token_expires_at'], name='ig_cred_status_exp_idx')],
            },
        ),
    ]
