from .models import EmailEventType


EMAIL_TEMPLATE_MAP = {
    EmailEventType.ORGANIZATION_PLAN_WELCOME: "BREVO_TEMPLATE_WELCOME",
    EmailEventType.PLAN_EXPIRY_REMINDER: "BREVO_TEMPLATE_EXPIRY_REMINDER",
    EmailEventType.PLAN_EXPIRED: "BREVO_TEMPLATE_EXPIRED",
    EmailEventType.PLAN_RENEWED: "BREVO_TEMPLATE_RENEWED",
    EmailEventType.PLAN_ACTIVATED: "BREVO_TEMPLATE_ACTIVATED",
    EmailEventType.PLAN_CANCELLED: "BREVO_TEMPLATE_CANCELLED",
}