# Generated by Django 5.2.16 on 2026-08-29 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0015_alter_organizationsubscription_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('ORGANIZATION_PLAN_WELCOME', 'Organization Plan Welcome'), ('PLAN_EXPIRY_REMINDER', 'Plan Expiry Reminder'), ('PLAN_EXPIRED', 'Plan Expired'), ('PLAN_RENEWED', 'Plan Renewed'), ('PLAN_CANCELLED', 'Plan Cancelled')], db_index=True, max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=500)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_events', to='organizations.organization')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_events', to='organizations.organizationsubscription')),
            ],
            options={
                'db_table': 'notification_email_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'event_type'], name='email_event_org_type_idx'), models.Index(fields=['subscription', 'event_type'], name='email_event_sub_type_idx'), models.Index(fields=['status', 'created_at'], name='email_event_status_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('subscription', 'event_type'), name='unique_subscription_email_event')],
            },
        ),
    ]
