# Generated by Django 5.2.16 on 2026-08-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailevent',
            name='event_type',
            field=models.CharField(choices=[('ORGANIZATION_PLAN_WELCOME', 'Organization Plan Welcome'), ('PLAN_EXPIRY_REMINDER', 'Plan Expiry Reminder'), ('PLAN_EXPIRED', 'Plan Expired'), ('PLAN_RENEWED', 'Plan Renewed'), ('PLAN_CANCELLED', 'Plan Cancelled'), ('PLAN_ACTIVATED', 'Plan Activated')], db_index=True, max_length=50),
        ),
    ]
