# Generated by Django 5.2.16 on 2026-10-07 10:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activitylog_event_type'),
        ('notifications', '0002_alter_emailevent_event_type'),
        ('organizations', '0016_organizationsubscription_schedule_type'),
        ('posts', '0006_poststatus_unresolved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('FAILED_POST', 'Failed Post'), ('SUBSCRIPTION_EXPIRED', 'Subscription Expired'), ('SUBSCRIPTION_EXPIRING', 'Subscription Expiring Soon'), ('POST_PUBLISHED', 'Post Published'), ('SUBSCRIPTION_ACTIVATED', 'Subscription Activated')], db_index=True, max_length=40)),
                ('event_key', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=500)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='organizations.organization')),
                ('post_platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notifications', to='posts.postplatform')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('source_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notifications', to='activities.activitylog')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notifications', to='organizations.organizationsubscription')),
            ],
            options={
                'db_table': 'user_notifications',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='user_notif_rec_read_idx'), models.Index(fields=['recipient', 'resolved_at', '-created_at'], name='user_notif_rec_res_idx'), models.Index(fields=['post_platform', 'event_type', 'resolved_at'], name='user_notif_post_state_idx'), models.Index(fields=['subscription', 'event_type', 'resolved_at'], name='user_notif_sub_state_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('event_key__gt', ''), ('is_deleted', False)), fields=('event_key',), name='unique_active_user_notification_key')],
            },
        ),
    ]
