# Generated by Django 5.2.16 on 2026-09-04 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_accounts', '0003_socialconnection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAccountCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('credential_type', models.CharField(choices=[('user', 'User'), ('page', 'Page')], max_length=20)),
                ('access_token', models.TextField()),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('invalid', 'Invalid'), ('error', 'Error')], db_index=True, default='active', max_length=20)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('social_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_credential', to='social_accounts.socialaccount')),
            ],
            options={
                'db_table': 'meta_account_credentials',
                'indexes': [models.Index(fields=['status'], name='meta_cred_status_idx'), models.Index(fields=['token_expires_at'], name='meta_cred_expiry_idx')],
            },
        ),
    ]
