# Generated by Django 5.2.16 on 2026-09-04 10:18

import django.db.models.deletion
from django.db import migrations, models


def migrate_meta_credentials(apps, schema_editor):
    MetaAccountCredential = apps.get_model(
        "meta_integration",
        "MetaAccountCredential",
    )

    SocialConnection = apps.get_model(
        "social_accounts",
        "SocialConnection",
    )

    # Existing USER credentials were incorrectly attached
    # to SocialAccount during the previous token migration.
    #
    # Move them to the corresponding Meta SocialConnection.
    user_credentials = MetaAccountCredential.objects.filter(
        credential_type="user",
        social_account__isnull=False,
    ).select_related(
        "social_account",
    )

    for credential in user_credentials:
        social_account = credential.social_account

        connection = SocialConnection.objects.filter(
            id=social_account.connection_id,
            provider="meta",
            is_deleted=False,
        ).first()

        if connection is None:
            raise RuntimeError(
                f"Cannot migrate Meta USER credential {credential.pk}: "
                f"no active Meta SocialConnection found."
            )

        credential.social_connection_id = connection.id
        credential.social_account_id = None
        credential.save(
            update_fields=[
                "social_connection",
                "social_account",
                "updated_at",
            ]
        )


def reverse_migrate_meta_credentials(apps, schema_editor):
    """
    Reverse migration intentionally does not recreate the old
    incorrect USER credential ownership.

    Existing data is left untouched.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("meta_integration", "0001_initial"),
        ("social_accounts", "0004_migrate_meta_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="metaaccountcredential",
            name="social_connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meta_credentials",
                to="social_accounts.socialconnection",
            ),
        ),
        migrations.AlterField(
            model_name="metaaccountcredential",
            name="social_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meta_credential",
                to="social_accounts.socialaccount",
            ),
        ),
        migrations.RunPython(
            migrate_meta_credentials,
            reverse_migrate_meta_credentials,
        ),
        migrations.AddIndex(
            model_name="metaaccountcredential",
            index=models.Index(
                fields=[
                    "social_connection",
                    "credential_type",
                ],
                name="meta_cred_conn_type_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="metaaccountcredential",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        credential_type="user",
                        social_account__isnull=True,
                        social_connection__isnull=False,
                    )
                    | models.Q(
                        credential_type="page",
                        social_account__isnull=False,
                        social_connection__isnull=True,
                    )
                ),
                name="meta_credential_valid_owner",
            ),
        ),
    ]
