# Generated by Django 5.2.16 on 2026-09-07 11:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_integration', '0002_metaaccountcredential_social_connection_and_more'),
        ('organizations', '0016_organizationsubscription_schedule_type'),
        ('social_accounts', '0005_remove_socialconnection_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaSocialAccountLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('facebook_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_instagram_links_as_page', to='social_accounts.socialaccount')),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_page_links_as_instagram', to='social_accounts.socialaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_social_account_links', to='organizations.organization')),
            ],
            options={
                'db_table': 'meta_social_account_links',
                'indexes': [models.Index(fields=['organization', 'facebook_page'], name='meta_link_org_page_idx'), models.Index(fields=['organization', 'instagram_account'], name='meta_link_org_ig_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'facebook_page', 'instagram_account'), name='unique_active_meta_page_instagram_link'), models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'instagram_account'), name='unique_active_meta_instagram_account_link')],
            },
        ),
    ]
