# Generated by Django 5.2.16 on 2026-09-09 05:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_integration', '0003_metasocialaccountlink'),
        ('organizations', '0016_organizationsubscription_schedule_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaOAuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('selection_key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('encrypted_access_token', models.TextField()),
                ('encrypted_accounts', models.TextField()),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_oauth_sessions', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_oauth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meta_oauth_sessions',
                'indexes': [models.Index(fields=['organization', 'user'], name='meta_oauth_org_user_idx'), models.Index(fields=['expires_at'], name='meta_oauth_session_expiry_idx')],
            },
        ),
    ]
