# Generated by Django 5.2.16 on 2026-09-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_integration', '0004_metaoauthsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaaccountcredential',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('INVALID', 'Invalid'), ('ERROR', 'Error')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
