# Generated by Django 5.2.16 on 2026-09-26 06:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_accounts', '0005_remove_socialconnection_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightsAccountSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('since', models.DateField()),
                ('until', models.DateField()),
                ('api_version', models.CharField(max_length=16)),
                ('metrics', models.JSONField(default=dict)),
                ('follower_growth', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField()),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights_account_snapshots', to='social_accounts.socialaccount')),
            ],
            options={
                'db_table': 'insights_account_snapshots',
                'indexes': [models.Index(fields=['social_account', 'since', 'until'], name='ins_acct_snap_range_idx'), models.Index(fields=['fetched_at'], name='ins_acct_snap_fetched_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('social_account', 'since', 'until', 'api_version'), name='ins_acct_snap_unique_live'), models.CheckConstraint(condition=models.Q(('since__lte', models.F('until'))), name='ins_acct_snap_valid_range')],
            },
        ),
        migrations.CreateModel(
            name='InsightsMediaSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provider_media_id', models.CharField(max_length=255)),
                ('media_type', models.CharField(blank=True, max_length=32)),
                ('caption', models.TextField(blank=True)),
                ('permalink', models.URLField(blank=True, max_length=2048)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('api_version', models.CharField(max_length=16)),
                ('metrics', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField()),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights_media_snapshots', to='social_accounts.socialaccount')),
            ],
            options={
                'db_table': 'insights_media_snapshots',
                'indexes': [models.Index(fields=['social_account', 'published_at', 'provider_media_id'], name='ins_media_snap_pub_idx'), models.Index(fields=['social_account', 'fetched_at'], name='ins_media_snap_fetched_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('social_account', 'provider_media_id'), name='ins_media_snap_unique_live')],
            },
        ),
        migrations.CreateModel(
            name='InsightsSyncState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('since', models.DateField()),
                ('until', models.DateField()),
                ('api_version', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('syncing', 'Syncing'), ('complete', 'Complete'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('provider_cursor', models.TextField(blank=True)),
                ('items_discovered', models.PositiveIntegerField(default=0)),
                ('items_processed', models.PositiveIntegerField(default=0)),
                ('items_total', models.PositiveIntegerField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_reason', models.CharField(blank=True, max_length=255)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights_sync_states', to='social_accounts.socialaccount')),
            ],
            options={
                'db_table': 'insights_sync_states',
                'indexes': [models.Index(fields=['status', 'requested_at'], name='ins_sync_status_req_idx'), models.Index(fields=['social_account', 'since', 'until'], name='ins_sync_account_range_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status__in', ('queued', 'syncing'))), fields=('social_account', 'since', 'until'), name='ins_sync_unique_active'), models.CheckConstraint(condition=models.Q(('since__lte', models.F('until'))), name='ins_sync_valid_range'), models.CheckConstraint(condition=models.Q(('items_processed__lte', models.F('items_discovered'))), name='ins_sync_processed_le_discovered'), models.CheckConstraint(condition=models.Q(('items_total__isnull', True), ('items_processed__lte', models.F('items_total')), _connector='OR'), name='ins_sync_processed_le_total')],
            },
        ),
    ]
