# Generated by Django 5.2.16 on 2026-09-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightsaccountsnapshot',
            name='profile_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='insightssyncstate',
            name='account_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insightssyncstate',
            name='account_error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='insightssyncstate',
            name='account_error_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='insightssyncstate',
            name='account_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insightssyncstate',
            name='account_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('syncing', 'Syncing'), ('complete', 'Complete'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16),
        ),
        migrations.AddField(
            model_name='insightssyncstate',
            name='checkpoint',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='insightsmediasnapshot',
            name='fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
