# Generated by Django 5.2.16 on 2026-10-05 05:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0004_insightssyncwork'),
        ('social_accounts', '0006_alter_socialaccount_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightsContentSnapshotItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provider_media_id', models.CharField(max_length=255)),
                ('media_type', models.CharField(blank=True, max_length=32)),
                ('caption', models.TextField(blank=True)),
                ('permalink', models.URLField(blank=True, max_length=2048)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('api_version', models.CharField(max_length=16)),
                ('metrics', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'insights_content_snapshot_items',
            },
        ),
        migrations.CreateModel(
            name='InsightsSnapshotSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('duration_days', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'insights_snapshot_slots',
            },
        ),
        migrations.RemoveConstraint(
            model_name='insightsaccountsnapshot',
            name='ins_acct_snap_unique_live',
        ),
        migrations.AddField(
            model_name='insightsaccountsnapshot',
            name='sync_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_snapshots', to='insights.insightssyncstate'),
        ),
        migrations.AddField(
            model_name='insightssyncstate',
            name='content_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='insightsaccountsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('sync_state__isnull', True)), fields=('social_account', 'since', 'until', 'api_version'), name='ins_acct_snap_legacy_uniq'),
        ),
        migrations.AddConstraint(
            model_name='insightsaccountsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('sync_state__isnull', False)), fields=('sync_state', 'api_version'), name='ins_acct_snap_version_uniq'),
        ),
        migrations.AddField(
            model_name='insightscontentsnapshotitem',
            name='sync_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_snapshot_items', to='insights.insightssyncstate'),
        ),
        migrations.AddField(
            model_name='insightssnapshotslot',
            name='active_sync_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_snapshot_slots', to='insights.insightssyncstate'),
        ),
        migrations.AddField(
            model_name='insightssnapshotslot',
            name='published_account_sync_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_account_snapshot_slots', to='insights.insightssyncstate'),
        ),
        migrations.AddField(
            model_name='insightssnapshotslot',
            name='published_content_sync_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_content_snapshot_slots', to='insights.insightssyncstate'),
        ),
        migrations.AddField(
            model_name='insightssnapshotslot',
            name='social_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights_snapshot_slots', to='social_accounts.socialaccount'),
        ),
        migrations.AddIndex(
            model_name='insightscontentsnapshotitem',
            index=models.Index(fields=['sync_state', 'published_at', 'provider_media_id'], name='ins_content_state_pub_idx'),
        ),
        migrations.AddConstraint(
            model_name='insightscontentsnapshotitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('sync_state', 'provider_media_id'), name='ins_content_state_media_uniq'),
        ),
        migrations.AddConstraint(
            model_name='insightssnapshotslot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('social_account', 'duration_days'), name='ins_snap_slot_account_days_uniq'),
        ),
        migrations.AddConstraint(
            model_name='insightssnapshotslot',
            constraint=models.CheckConstraint(condition=models.Q(('duration_days__in', (7, 28, 30))), name='ins_snap_slot_days_valid'),
        ),
    ]
