# Generated by Django 5.2.16 on 2026-08-25 08:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0013_sync_subscription_migration_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentIdea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('platform', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('YOUTUBE', 'YouTube'), ('LINKEDIN', 'LinkedIn'), ('X', 'X (Twitter)')], db_index=True, max_length=20)),
                ('content_type', models.CharField(choices=[('POST', 'Post'), ('REEL', 'Reel'), ('STORY', 'Story'), ('CAROUSEL', 'Carousel'), ('SHORT', 'Short'), ('VIDEO', 'Video')], db_index=True, max_length=20)),
                ('campaign_goal', models.CharField(choices=[('BRAND_AWARENESS', 'Brand Awareness'), ('ENGAGEMENT', 'Engagement'), ('LEAD_GENERATION', 'Lead Generation'), ('WEBSITE_TRAFFIC', 'Website Traffic'), ('SALES', 'Sales')], db_index=True, max_length=30)),
                ('target_publish_date', models.DateField(db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_ideas', to='organizations.organization')),
            ],
            options={
                'db_table': 'content_ideas',
                'ordering': ['target_publish_date', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'target_publish_date'], name='content_idea_org_date_idx'), models.Index(fields=['platform', 'target_publish_date'], name='content_idea_platform_date_idx'), models.Index(fields=['campaign_goal', 'target_publish_date'], name='content_idea_goal_date_idx')],
            },
        ),
    ]
