# Generated by Django 5.2.16 on 2026-08-20 07:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organizationcontact_organizationsubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asset_type', models.CharField(choices=[('logo', 'Logo'), ('cover', 'Cover'), ('favicon', 'Favicon'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='organizations/brand-assets/')),
                ('is_primary', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_assets', to='organizations.organization')),
            ],
            options={
                'db_table': 'brand_assets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'asset_type'], name='brand_org_type_idx')],
            },
        ),
    ]
