# Generated by Django 5.2.16 on 2026-08-21 08:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('accounts_limit', models.PositiveIntegerField(default=0)),
                ('posts_limit', models.PositiveIntegerField(default=0)),
                ('videos_limit', models.PositiveIntegerField(default=0)),
                ('ads_limit', models.PositiveIntegerField(default=0)),
                ('dm_automations_limit', models.PositiveIntegerField(default=0)),
                ('highlights', models.TextField(blank=True, max_length=1000)),
                ('is_system', models.BooleanField(db_index=True, default=False)),
                ('is_custom', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'plans',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='plan_status_created_idx'), models.Index(fields=['is_system'], name='plan_system_idx')],
            },
        ),
    ]
