# Generated by Django 5.2.16 on 2026-08-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plan_plan_type_plan_plan_type_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
