# Generated by Django 5.2.16 on 2026-08-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_plan_plan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='billing_cycle',
        ),
    ]
