# Generated by Django 5.2.16 on 2026-08-20 07:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organizationcontact_organizationsubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('threads', 'Threads'), ('x', 'X'), ('youtube', 'YouTube')], max_length=20)),
                ('platform_account_id', models.CharField(max_length=255)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('profile_image', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('expired', 'Expired'), ('error', 'Error')], db_index=True, default='disconnected', max_length=20)),
                ('is_valid', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='organizations.organization')),
            ],
            options={
                'db_table': 'social_accounts',
                'ordering': ['platform', 'account_name'],
                'indexes': [models.Index(fields=['organization', 'platform'], name='social_org_platform_idx'), models.Index(fields=['status'], name='social_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'platform', 'platform_account_id'), name='unique_social_account_per_org_platform')],
            },
        ),
    ]
