# Generated by Django 5.2.16 on 2026-08-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_alter_organizationsubscription_organization'),
        ('social_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='socialaccount',
            name='unique_social_account_per_org_platform',
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'platform'), name='unique_active_social_platform_per_org'),
        ),
    ]
