# Generated by Django 5.2.16 on 2026-09-02 09:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_organizationsubscription_schedule_type'),
        ('social_accounts', '0002_remove_socialaccount_unique_social_account_per_org_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(choices=[('meta', 'Meta')], max_length=20)),
                ('provider_user_id', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('error', 'Error')], db_index=True, default='active', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'social_connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='socialaccount',
            name='unique_active_social_platform_per_org',
        ),
        migrations.RemoveIndex(
            model_name='socialaccount',
            name='social_status_idx',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='token_expires_at',
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='is_valid',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='socialconnection',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_connections', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='social_accounts', to='social_accounts.socialconnection'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['organization', 'status'], name='social_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['platform', 'platform_account_id'], name='social_platform_account_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'platform', 'platform_account_id'), name='unique_org_platform_account'),
        ),
        migrations.AddIndex(
            model_name='socialconnection',
            index=models.Index(fields=['organization', 'provider'], name='social_conn_org_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='socialconnection',
            index=models.Index(fields=['status'], name='social_conn_status_idx'),
        ),
        migrations.AddIndex(
            model_name='socialconnection',
            index=models.Index(fields=['token_expires_at'], name='social_conn_token_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('provider_user_id', ''), _negated=True)), fields=('organization', 'provider', 'provider_user_id'), name='unique_org_provider_user_connection'),
        ),
    ]
