# Generated by Django 5.2.16 on 2026-09-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0004_migrate_meta_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialconnection',
            name='access_token',
        ),
    ]
