# Generated by Django 5.2.16 on 2026-09-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0005_remove_socialconnection_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='profile_image',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
