# Generated by Django 5.2.16 on 2026-10-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('ORGANIZATION_CREATED', 'Organization Created'), ('SUBSCRIPTION_ACTIVATED', 'Subscription Activated'), ('POST_CREATED', 'Post Created'), ('POST_SCHEDULED', 'Post Scheduled'), ('POST_PUBLISHED', 'Post Published'), ('POST_FAILED', 'Post Failed'), ('SUBSCRIPTION_RENEWED', 'Subscription Renewed'), ('SUBSCRIPTION_CANCELLED', 'Subscription Cancelled'), ('SUBSCRIPTION_EXPIRING', 'Subscription Expiring Soon'), ('SUBSCRIPTION_EXPIRED', 'Subscription Expired')], db_index=True, max_length=50),
        ),
    ]
