# Generated by Django 5.2.16 on 2026-08-27 05:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0015_alter_organizationsubscription_organization'),
        ('social_accounts', '0002_remove_socialaccount_unique_social_account_per_org_platform_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('caption', models.TextField(blank=True)),
                ('publish_type', models.CharField(choices=[('DRAFT', 'Draft'), ('NOW', 'Publish Now'), ('SCHEDULE', 'Schedule')], db_index=True, default='DRAFT', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHING', 'Publishing'), ('PUBLISHED', 'Published'), ('PARTIALLY_PUBLISHED', 'Partially Published'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=100)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_posts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='organizations.organization')),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='posts/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='posts.post')),
            ],
            options={
                'db_table': 'post_media',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostPlatform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('threads', 'Threads'), ('x', 'X'), ('youtube', 'YouTube')], max_length=20)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHING', 'Publishing'), ('PUBLISHED', 'Published'), ('PARTIALLY_PUBLISHED', 'Partially Published'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30)),
                ('external_post_id', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='posts.post')),
                ('social_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_platforms', to='social_accounts.socialaccount')),
            ],
            options={
                'db_table': 'post_platforms',
                'ordering': ['platform'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['organization', 'status'], name='post_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['organization', 'publish_type'], name='post_org_type_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['scheduled_at'], name='post_scheduled_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_by'], name='post_created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='postmedia',
            index=models.Index(fields=['post', 'sort_order'], name='post_media_order_idx'),
        ),
        migrations.AddIndex(
            model_name='postmedia',
            index=models.Index(fields=['media_type'], name='post_media_type_idx'),
        ),
        migrations.AddIndex(
            model_name='postplatform',
            index=models.Index(fields=['post', 'platform'], name='post_platform_idx'),
        ),
        migrations.AddIndex(
            model_name='postplatform',
            index=models.Index(fields=['social_account'], name='post_social_account_idx'),
        ),
        migrations.AddIndex(
            model_name='postplatform',
            index=models.Index(fields=['status'], name='post_platform_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='postplatform',
            constraint=models.UniqueConstraint(fields=('post', 'platform'), name='unique_platform_per_post'),
        ),
    ]
