# Generated by Django 5.2.16 on 2026-09-05 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('social_accounts', '0005_remove_socialconnection_access_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postplatform',
            options={'ordering': ['platform', 'created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='postplatform',
            name='unique_platform_per_post',
        ),
        migrations.AlterField(
            model_name='postplatform',
            name='social_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post_platforms', to='social_accounts.socialaccount'),
        ),
        migrations.AddConstraint(
            model_name='postplatform',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('social_account__isnull', False)), fields=('post', 'social_account'), name='unique_active_post_social_account'),
        ),
    ]
