# Generated by Django 5.2.16 on 2026-09-16

import uuid

from django.db import migrations, models


def populate_idempotency_keys(apps, schema_editor):
    """Give every pre-existing publishing target a stable unique key."""
    PostPlatform = apps.get_model("posts", "PostPlatform")

    for post_platform in PostPlatform.objects.filter(
        idempotency_key__isnull=True,
    ).iterator(chunk_size=500):
        post_platform.idempotency_key = uuid.uuid5(
            uuid.NAMESPACE_URL,
            f"posts.postplatform.idempotency_key:{post_platform.pk}",
        )
        post_platform.save(update_fields=["idempotency_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_postplatform_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postplatform",
            name="attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="postplatform",
            name="idempotency_key",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(
            populate_idempotency_keys,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="postplatform",
            name="idempotency_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="postplatform",
            name="provider_container_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="postplatform",
            name="publish_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
