# Generated by Django 5.2.16 on 2026-09-17 05:13

import apps.posts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postplatform_publish_execution_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='postplatform',
            name='provider_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(storage=apps.posts.storage.PostMediaCloudinaryStorage(), upload_to='posts/%Y/%m/%d/'),
        ),
    ]
