# Generated by Django 5.2.16 on 2026-09-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_postplatform_provider_state_alter_postmedia_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="postplatform",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="postplatform",
            name="scheduled_timezone",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
