# Generated by Django 5.2.16 on 2026-09-21

from django.db import migrations, models


AMBIGUOUS_INSTAGRAM_PUBLISH_PREFIX = "Instagram publish outcome could not be confirmed."


def move_ambiguous_instagram_targets_to_unresolved(apps, schema_editor):
    PostPlatform = apps.get_model("posts", "PostPlatform")
    PostPlatform.objects.filter(
        status="PUBLISHING",
        error_message__startswith=AMBIGUOUS_INSTAGRAM_PUBLISH_PREFIX,
    ).update(status="UNRESOLVED")


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_postplatform_scheduled_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SCHEDULED", "Scheduled"),
                    ("PUBLISHING", "Publishing"),
                    ("UNRESOLVED", "Unresolved"),
                    ("PUBLISHED", "Published"),
                    ("PARTIALLY_PUBLISHED", "Partially Published"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="postplatform",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SCHEDULED", "Scheduled"),
                    ("PUBLISHING", "Publishing"),
                    ("UNRESOLVED", "Unresolved"),
                    ("PUBLISHED", "Published"),
                    ("PARTIALLY_PUBLISHED", "Partially Published"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.RunPython(
            move_ambiguous_instagram_targets_to_unresolved,
            migrations.RunPython.noop,
        ),
    ]
