# Generated by Django 5.2.16 on 2026-08-20 07:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'organization_contacts',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.CharField(choices=[('BASIC', 'Basic'), ('ADVANCE', 'Advance'), ('CUSTOM', 'Custom')], default='BASIC', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organization_subscriptions',
            },
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='phone',
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_id',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status', '-created_at'], name='org_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['industry'], name='org_industry_idx'),
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='organizationcontact',
            index=models.Index(fields=['organization', 'is_primary'], name='org_contact_primary_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationcontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('organization',), name='unique_primary_contact_per_org'),
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['status'], name='org_sub_status_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['expiry_date'], name='org_sub_expiry_idx'),
        ),
    ]
