# Generated by Django 5.2.16 on 2026-08-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationcontact_organizationsubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo_color',
            field=models.CharField(default='#3563F6', max_length=20),
        ),
    ]
