# Generated by Django 5.2.16 on 2026-08-22 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_migrate_subscription_plans'),
        ('plans', '0004_remove_plan_billing_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsubscription',
            name='plan_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_subscription_references', to='plans.plan'),
        ),
    ]
