# Generated by Django 5.2.16 on 2026-08-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_alter_organizationsubscription_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsubscription',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[('renewal', 'Renewal'), ('plan_change', 'Plan Change')], db_index=True, default=None, max_length=20, null=True),
        ),
    ]
